#' Ancestral Condition Test (Parametric Bootstrap)
#'
#' A more rigorous version of \code{\link{AncCond}} that builds its null
#' distribution using parametric bootstrapping instead of simple node
#' resampling.  This means the null is generated by simulating entire
#' neutral evolutionary histories on the tree, which better accounts for
#' phylogenetic structure and mapping uncertainty.
#'
#' \strong{When should you use this instead of \code{\link{AncCond}}?}
#' Use this function when you want a stricter statistical test.  The
#' parametric bootstrap simulates new discrete traits that evolve
#' independently of the continuous trait (i.e., the null hypothesis) and
#' puts each simulation through the exact same stochastic-mapping pipeline
#' as the real data.
#'
#' \strong{What does "parametric bootstrap" mean here?}
#' Instead of shuffling real node values to build a null distribution,
#' this function:
#' \enumerate{
#'   \item Fits a transition rate matrix (Q) to the observed discrete trait.
#'   \item Simulates new "neutral" discrete traits on the tree using that Q
#'         matrix (via \code{\link[phytools]{sim.history}}).
#'   \item For each simulated trait, runs multiple stochastic maps and
#'         calculates the mean continuous value at transition nodes.
#'   \item Compares the real Grand Mean to the distribution of neutral
#'         Grand Means.
#' }
#'
#' A \code{filter_tol} parameter ensures that only simulations producing
#' a similar number of derived-state tips as the real data are kept,
#' preventing biologically unreasonable null simulations.
#'
#' @param tree A phylogenetic tree of class \code{"phylo"}.
#' @param data A data frame with exactly 3 columns:
#'   \enumerate{
#'     \item \strong{Tip labels} -- must match \code{tree$tip.label}.
#'     \item \strong{Continuous trait} -- numeric values (e.g., body size).
#'     \item \strong{Discrete trait} -- coded as 1 (ancestral) and 2
#'           (derived).
#'   }
#'   No missing data allowed; prune any incomplete taxa first.
#' @param n_iter Integer.  Number of valid neutral simulations to collect
#'   for the null distribution (default 100).  More iterations give a
#'   smoother null but take longer.
#' @param n_maps Integer.  Number of stochastic maps to average over per
#'   simulation (default 100).  This integrates over mapping uncertainty
#'   so you are not relying on a single random map.
#' @param drop.state \code{NULL} (default), \code{1}, or \code{2}.  If set,
#'   tips in this state are excluded before reconstructing ancestral
#'   continuous values.  This prevents evolutionary feedback: if being in
#'   state 2 causes the continuous trait to change, you don't want those
#'   changed values biasing the ancestral estimates.
#' @param filter_tol Numeric.  Tolerance for accepting neutral simulations
#'   (default 0.2, meaning 20\%).
#'   A simulated trait is kept only if its count of state-2 tips is within
#'   \code{+/- filter_tol} of the empirical count.  This prevents
#'   pathological simulations where almost all (or no) tips are in state 2.
#' @param mat Transition model passed to \code{\link[phytools]{make.simmap}}.
#'   Can be \code{"ARD"} (all rates different, the default), \code{"ER"}
#'   (equal rates), or a custom rate matrix.
#' @param pi Root state prior for the discrete trait.  Options:
#'   \code{"equal"} (default), \code{"estimated"}, or a numeric vector of
#'   length 2 summing to 1.
#' @param message Logical.  If \code{TRUE} (default), progress updates and
#'   a formatted results table are printed to the console.
#'
#' @return An invisible list with:
#'   \describe{
#'     \item{obs_stat}{The observed Grand Mean -- the average continuous
#'       trait value at nodes where 1 -> 2 transitions occurred, averaged
#'       across all stochastic maps of the real data.}
#'     \item{null_dist}{Numeric vector of Grand Means from neutral
#'       simulations (length = \code{n_iter} or fewer if the failsafe
#'       triggered).}
#'     \item{p_value}{Two-tailed p-value.}
#'     \item{pct_higher}{Percent of null values above the observed.}
#'     \item{pct_lower}{Percent of null values below the observed.}
#'     \item{sim_attempts}{Total simulations attempted (including
#'       rejected ones).}
#'     \item{valid_sims}{Number of simulations that passed the filter.}
#'   }
#'
#' @seealso \code{\link{AncCond}} for the original Monte Carlo resampling
#'   version, which is faster but less rigorous.
#'
#' @examples
#' \dontrun{
#' library(ape)
#' library(phytools)
#' tree <- rcoal(30)
#' data <- data.frame(
#'   species = tree$tip.label,
#'   body_size = rnorm(30, 10, 2),
#'   has_horn = sample(1:2, 30, replace = TRUE)
#' )
#' # Run parametric bootstrap with 50 null simulations, 50 maps each
#' result <- AncCondFast(tree, data, n_iter = 50, n_maps = 50)
#' hist(result$null_dist, main = "Null Distribution")
#' abline(v = result$obs_stat, col = "red", lwd = 2)
#' }
#'
#' @importFrom phytools anc.ML matchNodes make.simmap fitMk sim.history
#' @importFrom ape drop.tip Nnode
#' @export
AncCondFast <- function(tree, data, n_iter = 100, n_maps = 100,
                    drop.state = NULL, filter_tol = 0.2,
                    mat = "ARD", pi = "equal", message = TRUE) {

  # =========================================================================
  # 1. DATA VALIDATION & PREPARATION
  # =========================================================================
  if (!inherits(tree, "phylo")) stop("Tree must be class 'phylo'")

  # Enforce strict alignment between the phylogeny and the dataset
  rownames(data) <- data[, 1]
  data <- data[tree$tip.label, ]
  if (any(is.na(data))) stop("Data contains NAs. Prune tree prior to analysis.")

  # Extract named vectors for fast indexing later
  cont_vec <- setNames(as.numeric(data[, 2]), data[, 1])
  disc_vec <- setNames(as.numeric(data[, 3]), data[, 1])

  if (!all(unique(disc_vec) %in% c(1, 2))) stop("Discrete trait must be coded as 1 and 2.")

  # =========================================================================
  # 2. CONTINUOUS ANCESTRAL STATE RECONSTRUCTION
  # =========================================================================
  # This is calculated once from the real data and reused for all simulations,
  # because the continuous trait is held fixed under the null hypothesis.
  if (message) cat("-> Reconstructing continuous ancestral states via Maximum Likelihood...\n")

  if (!is.null(drop.state)) {
    # Prune tips in the dropped state so their derived continuous values
    # don't bias the BM ancestral reconstruction
    keep_tips <- names(disc_vec)[disc_vec != drop.state]
    if (length(keep_tips) < 5) {
      stop("Too few tips left after drop.state pruning (need at least 5).")
    }

    pruned_tree <- drop.tip(tree, setdiff(tree$tip.label, keep_tips))
    cont_sub <- cont_vec[keep_tips]

    # Estimate on the pruned tree using Brownian motion
    anc_obj <- anc.ML(pruned_tree, cont_sub, model = "BM")

    # Map the pruned-tree node estimates back to the full tree
    full_node_vals <- rep(NA, Nnode(tree) + length(tree$tip.label))
    matches <- matchNodes(tree, pruned_tree)
    full_node_vals[matches[, 1]] <- anc_obj$ace[as.character(matches[, 2])]

    # Isolate internal node values (where transitions happen)
    internal_vals <- full_node_vals[(length(tree$tip.label) + 1):length(full_node_vals)]
    names(internal_vals) <- (length(tree$tip.label) + 1):length(full_node_vals)

  } else {
    # Standard BM estimation on the full tree
    anc_obj <- anc.ML(tree, cont_vec, model = "BM")
    internal_vals <- anc_obj$ace
  }

  # =========================================================================
  # 3. HELPER: GRAND MEAN CALCULATOR
  # =========================================================================
  # Takes a discrete trait vector, runs N stochastic maps, finds the
  # parent nodes where 1->2 transitions occurred, and returns the mean
  # of their continuous ancestral values averaged across all maps.
  calc_grand_mean <- function(the_tree, the_vec, n_sims, model_mk) {

    # Run stochastic mapping (suppress console output for speed)
    sims <- make.simmap(the_tree, the_vec, model = model_mk,
                        nsim = n_sims, pi = pi, message = FALSE)
    if (inherits(sims, "simmap")) sims <- list(sims)

    means_1to2 <- numeric(length(sims))

    # Iterate through the posterior sample of maps
    for (i in seq_along(sims)) {
      edg <- sims[[i]]$edge

      # Get the state sequence on each branch
      state_seqs <- lapply(sims[[i]]$maps, names)

      # A 1->2 transition exists if "1" is immediately followed by "2"
      has_trans_12 <- vapply(state_seqs, function(nm) {
        any(nm[-length(nm)] == "1" & nm[-1] == "2")
      }, logical(1))

      # The producing node is the parent (column 1) of the transitioning branch
      prod_nodes <- unique(edg[has_trans_12, 1])

      # Look up the pre-calculated continuous ML values at those nodes
      vals <- internal_vals[as.character(prod_nodes)]
      vals <- vals[!is.na(vals)]

      if (length(vals) > 0) {
        means_1to2[i] <- mean(vals)
      } else {
        means_1to2[i] <- NA
      }
    }
    # Grand Mean integrates across the mapping uncertainty
    return(mean(means_1to2, na.rm = TRUE))
  }

  # =========================================================================
  # 4. EMPIRICAL GRAND MEAN
  # =========================================================================
  if (message) {
    cat(sprintf("-> Integrating empirical mapping uncertainty across %d stochastic maps...\n", n_maps))
  }

  # Fit the Mk model to extract the transition rate matrix (Q)
  # This same Q is used for both empirical mapping and neutral simulations
  q_fit <- fitMk(tree, disc_vec, model = mat)
  Q_emp <- q_fit$rates
  Q_mat <- matrix(0, 2, 2, dimnames = list(c("1", "2"), c("1", "2")))
  if (length(Q_emp) == 1) {
    Q_mat[1, 2] <- Q_mat[2, 1] <- Q_emp
  } else {
    Q_mat[1, 2] <- Q_emp[1]
    Q_mat[2, 1] <- Q_emp[2]
  }
  diag(Q_mat) <- -rowSums(Q_mat)

  # Calculate the observed statistic
  obs_grand_mean <- calc_grand_mean(tree, disc_vec, n_maps, Q_mat)

  # =========================================================================
  # 5. PARAMETRIC BOOTSTRAP (NULL DISTRIBUTION)
  # =========================================================================
  if (message) {
    cat(sprintf("-> Generating %d valid neutral simulations for the null distribution...\n", n_iter))
  }

  null_means <- numeric(n_iter)
  valid_sims <- 0
  total_sims <- 0

  # Filter boundaries: simulated data must have a similar number of
  # state-2 tips as the real data (within +/- filter_tol)
  n_tips_2 <- sum(disc_vec == 2)
  lower_bound <- n_tips_2 * (1 - filter_tol)
  upper_bound <- n_tips_2 * (1 + filter_tol)

  # Keep simulating until we have enough valid neutral replicates
  while (valid_sims < n_iter) {
    total_sims <- total_sims + 1

    # Simulate a neutral discrete trait (independent of continuous trait)
    sim_obj <- sim.history(tree, Q_mat, anc = "1", message = FALSE)
    sim_tips <- sim_obj$states

    # Only keep simulations that resemble empirical state frequencies
    count_2 <- sum(sim_tips == "2")
    if (count_2 >= lower_bound && count_2 <= upper_bound) {

      gm <- calc_grand_mean(tree, sim_tips, n_maps, Q_mat)

      if (!is.na(gm)) {
        valid_sims <- valid_sims + 1
        null_means[valid_sims] <- gm
        if (message && valid_sims %% 10 == 0) {
          cat(sprintf("   [%d/%d] valid neutral simulations completed...\n", valid_sims, n_iter))
        }
      }
    }

    # Failsafe: prevent infinite loops if the Q-matrix produces extreme data
    if (total_sims > n_iter * 50) {
      warning("Acceptance rate too low. Consider increasing filter_tol or checking model parameters.")
      break
    }
  }

  # Trim in case the failsafe triggered early
  null_means <- null_means[1:valid_sims]

  # =========================================================================
  # 6. STATISTICAL EVALUATION
  # =========================================================================

  pct_higher <- (sum(null_means > obs_grand_mean) / valid_sims) * 100
  pct_lower  <- (sum(null_means < obs_grand_mean) / valid_sims) * 100
  pct_equal  <- (sum(null_means == obs_grand_mean) / valid_sims) * 100

  # Two-tailed p-value
  p_val <- 2 * min(pct_higher / 100, pct_lower / 100)
  if (p_val > 1) p_val <- 1.0

  if (message) {
    cat("\n============================================================\n")
    cat("              ANCESTRAL CONDITION TEST RESULTS              \n")
    cat("============================================================\n")
    cat(sprintf(" Empirical Grand Mean (Observed) : %10.4f\n", obs_grand_mean))
    cat(sprintf(" Null Grand Mean (Expected)      : %10.4f\n", mean(null_means)))
    cat("------------------------------------------------------------\n")
    cat(sprintf(" Null Distribution (n = %d valid sims):\n", valid_sims))
    cat(sprintf("   -> %5.1f%% of neutral histories had a HIGHER ancestral condition.\n", pct_higher))
    cat(sprintf("   -> %5.1f%% of neutral histories had a LOWER  ancestral condition.\n", pct_lower))
    if (pct_equal > 0) {
      cat(sprintf("   -> %5.1f%% of neutral histories had an EQUAL ancestral condition.\n", pct_equal))
    }
    cat("------------------------------------------------------------\n")
    cat(sprintf(" Two-Tailed P-Value              : %10.4f\n", p_val))
    cat(sprintf(" Total Simulations Attempted     : %10d\n", total_sims))
    cat("============================================================\n\n")
  }

  invisible(list(
    obs_stat    = obs_grand_mean,
    null_dist   = null_means,
    p_value     = p_val,
    pct_higher  = pct_higher,
    pct_lower   = pct_lower,
    sim_attempts = total_sims,
    valid_sims  = valid_sims
  ))
}
